//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftParameters {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Parametros : global::System.Configuration.ApplicationSettingsBase {
        
        private static Parametros defaultInstance = ((Parametros)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Parametros())));
        
        public static Parametros Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool controla_processos {
            get {
                return ((bool)(this["controla_processos"]));
            }
            set {
                this["controla_processos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool controla_entregas {
            get {
                return ((bool)(this["controla_entregas"]));
            }
            set {
                this["controla_entregas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int numero_caixa {
            get {
                return ((int)(this["numero_caixa"]));
            }
            set {
                this["numero_caixa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DSoft Delivery v1.4")]
        public string titulo {
            get {
                return ((string)(this["titulo"]));
            }
            set {
                this["titulo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pedido_caixa {
            get {
                return ((bool)(this["pedido_caixa"]));
            }
            set {
                this["pedido_caixa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\DSoft\\DSoftDelivery\\Relatorios\\")]
        public string relatorios {
            get {
                return ((string)(this["relatorios"]));
            }
            set {
                this["relatorios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool debito_automatico {
            get {
                return ((bool)(this["debito_automatico"]));
            }
            set {
                this["debito_automatico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dsoft_delivery14.png")]
        public string imagem_fundo {
            get {
                return ((string)(this["imagem_fundo"]));
            }
            set {
                this["imagem_fundo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dsoft_login14.png")]
        public string imagem_login {
            get {
                return ((string)(this["imagem_login"]));
            }
            set {
                this["imagem_login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impressora {
            get {
                return ((string)(this["impressora"]));
            }
            set {
                this["impressora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool imp2vias {
            get {
                return ((bool)(this["imp2vias"]));
            }
            set {
                this["imp2vias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool imprime_ticket {
            get {
                return ((bool)(this["imprime_ticket"]));
            }
            set {
                this["imprime_ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string promocao1 {
            get {
                return ((string)(this["promocao1"]));
            }
            set {
                this["promocao1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string promocao2 {
            get {
                return ((string)(this["promocao2"]));
            }
            set {
                this["promocao2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dupla_linha {
            get {
                return ((bool)(this["dupla_linha"]));
            }
            set {
                this["dupla_linha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool produto_por_nome {
            get {
                return ((bool)(this["produto_por_nome"]));
            }
            set {
                this["produto_por_nome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool imprime_producao {
            get {
                return ((bool)(this["imprime_producao"]));
            }
            set {
                this["imprime_producao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PIZZARIA")]
        public string ramo {
            get {
                return ((string)(this["ramo"]));
            }
            set {
                this["ramo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool registra_vendedor {
            get {
                return ((bool)(this["registra_vendedor"]));
            }
            set {
                this["registra_vendedor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/dsoft/CTe/")]
        public string pasta_cte {
            get {
                return ((string)(this["pasta_cte"]));
            }
            set {
                this["pasta_cte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/dsoft/projetos/dsoft delivery/cte/cte_v1.03.xsd")]
        public string schema_cte {
            get {
                return ((string)(this["schema_cte"]));
            }
            set {
                this["schema_cte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool emite_cupom_fiscal {
            get {
                return ((bool)(this["emite_cupom_fiscal"]));
            }
            set {
                this["emite_cupom_fiscal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWEDA")]
        public string ecf {
            get {
                return ((string)(this["ecf"]));
            }
            set {
                this["ecf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string ecf_porta {
            get {
                return ((string)(this["ecf_porta"]));
            }
            set {
                this["ecf_porta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string schema_status_servico {
            get {
                return ((string)(this["schema_status_servico"]));
            }
            set {
                this["schema_status_servico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Program Files (x86)/PostgreSQL/9.1/bin/")]
        public string postgresql {
            get {
                return ((string)(this["postgresql"]));
            }
            set {
                this["postgresql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/dsoft/backup/")]
        public string backup {
            get {
                return ((string)(this["backup"]));
            }
            set {
                this["backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool leitora_barras {
            get {
                return ((bool)(this["leitora_barras"]));
            }
            set {
                this["leitora_barras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pasta_cte_retorno {
            get {
                return ((string)(this["pasta_cte_retorno"]));
            }
            set {
                this["pasta_cte_retorno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pasta_cte_erro {
            get {
                return ((string)(this["pasta_cte_erro"]));
            }
            set {
                this["pasta_cte_erro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pasta_cte_assinadas {
            get {
                return ((string)(this["pasta_cte_assinadas"]));
            }
            set {
                this["pasta_cte_assinadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pasta_cte_enviadas {
            get {
                return ((string)(this["pasta_cte_enviadas"]));
            }
            set {
                this["pasta_cte_enviadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pasta_cte_negadas {
            get {
                return ((string)(this["pasta_cte_negadas"]));
            }
            set {
                this["pasta_cte_negadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pasta_cte_arquivo {
            get {
                return ((string)(this["pasta_cte_arquivo"]));
            }
            set {
                this["pasta_cte_arquivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool matriz {
            get {
                return ((bool)(this["matriz"]));
            }
            set {
                this["matriz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string matriz_servidor {
            get {
                return ((string)(this["matriz_servidor"]));
            }
            set {
                this["matriz_servidor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long matriz_porta {
            get {
                return ((long)(this["matriz_porta"]));
            }
            set {
                this["matriz_porta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int matriz_intervalo {
            get {
                return ((int)(this["matriz_intervalo"]));
            }
            set {
                this["matriz_intervalo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string matriz_pasta {
            get {
                return ((string)(this["matriz_pasta"]));
            }
            set {
                this["matriz_pasta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fecha_caixa_automatico {
            get {
                return ((bool)(this["fecha_caixa_automatico"]));
            }
            set {
                this["fecha_caixa_automatico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double caixa_inicial {
            get {
                return ((double)(this["caixa_inicial"]));
            }
            set {
                this["caixa_inicial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int licenca_aviso {
            get {
                return ((int)(this["licenca_aviso"]));
            }
            set {
                this["licenca_aviso"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int impressora_colunas {
            get {
                return ((int)(this["impressora_colunas"]));
            }
            set {
                this["impressora_colunas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/dsoft/log/")]
        public string pasta_log {
            get {
                return ((string)(this["pasta_log"]));
            }
            set {
                this["pasta_log"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome.exe")]
        public string browser {
            get {
                return ((string)(this["browser"]));
            }
            set {
                this["browser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool relatorios_matricial {
            get {
                return ((bool)(this["relatorios_matricial"]));
            }
            set {
                this["relatorios_matricial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int aviso_estoque {
            get {
                return ((int)(this["aviso_estoque"]));
            }
            set {
                this["aviso_estoque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bloqueia_estoque {
            get {
                return ((bool)(this["bloqueia_estoque"]));
            }
            set {
                this["bloqueia_estoque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bloqueia_cliente_anonimo {
            get {
                return ((bool)(this["bloqueia_cliente_anonimo"]));
            }
            set {
                this["bloqueia_cliente_anonimo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe {
            get {
                return ((string)(this["nfe"]));
            }
            set {
                this["nfe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe_enviadas {
            get {
                return ((string)(this["nfe_enviadas"]));
            }
            set {
                this["nfe_enviadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe_retorno {
            get {
                return ((string)(this["nfe_retorno"]));
            }
            set {
                this["nfe_retorno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe_gravados {
            get {
                return ((string)(this["nfe_gravados"]));
            }
            set {
                this["nfe_gravados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe_temporarios {
            get {
                return ((string)(this["nfe_temporarios"]));
            }
            set {
                this["nfe_temporarios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe_backup {
            get {
                return ((string)(this["nfe_backup"]));
            }
            set {
                this["nfe_backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe_validados {
            get {
                return ((string)(this["nfe_validados"]));
            }
            set {
                this["nfe_validados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nfe_baixados {
            get {
                return ((string)(this["nfe_baixados"]));
            }
            set {
                this["nfe_baixados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string schema_nfe {
            get {
                return ((string)(this["schema_nfe"]));
            }
            set {
                this["schema_nfe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mensagem_cupom {
            get {
                return ((string)(this["mensagem_cupom"]));
            }
            set {
                this["mensagem_cupom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool taxa_entrega_grupo {
            get {
                return ((bool)(this["taxa_entrega_grupo"]));
            }
            set {
                this["taxa_entrega_grupo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool imprime_usuario {
            get {
                return ((bool)(this["imprime_usuario"]));
            }
            set {
                this["imprime_usuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ordem_coleta_vias {
            get {
                return ((int)(this["ordem_coleta_vias"]));
            }
            set {
                this["ordem_coleta_vias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool verifica_arquivos {
            get {
                return ((bool)(this["verifica_arquivos"]));
            }
            set {
                this["verifica_arquivos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impressora_externa_1 {
            get {
                return ((string)(this["impressora_externa_1"]));
            }
            set {
                this["impressora_externa_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impressora_externa_2 {
            get {
                return ((string)(this["impressora_externa_2"]));
            }
            set {
                this["impressora_externa_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool permite_cancelamento {
            get {
                return ((bool)(this["permite_cancelamento"]));
            }
            set {
                this["permite_cancelamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mapas_online {
            get {
                return ((bool)(this["mapas_online"]));
            }
            set {
                this["mapas_online"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impressora_delivery {
            get {
                return ((string)(this["impressora_delivery"]));
            }
            set {
                this["impressora_delivery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/DSoft/memoriafiscal.mf")]
        public string ecf_downloadmf {
            get {
                return ((string)(this["ecf_downloadmf"]));
            }
            set {
                this["ecf_downloadmf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.1")]
        public string versao_postgresql {
            get {
                return ((string)(this["versao_postgresql"]));
            }
            set {
                this["versao_postgresql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x86")]
        public string processador_postgresql {
            get {
                return ((string)(this["processador_postgresql"]));
            }
            set {
                this["processador_postgresql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool impressora_corte {
            get {
                return ((bool)(this["impressora_corte"]));
            }
            set {
                this["impressora_corte"] = value;
            }
        }
    }
}
