//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftParameters {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Pref : global::System.Configuration.ApplicationSettingsBase {
        
        private static Pref defaultInstance = ((Pref)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Pref())));
        
        public static Pref Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string componente1 {
            get {
                return ((string)(this["componente1"]));
            }
            set {
                this["componente1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string componente2 {
            get {
                return ((string)(this["componente2"]));
            }
            set {
                this["componente2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string componente3 {
            get {
                return ((string)(this["componente3"]));
            }
            set {
                this["componente3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string componente4 {
            get {
                return ((string)(this["componente4"]));
            }
            set {
                this["componente4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection pedidos_colunas {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pedidos_colunas"]));
            }
            set {
                this["pedidos_colunas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int pedidos_atualiza {
            get {
                return ((int)(this["pedidos_atualiza"]));
            }
            set {
                this["pedidos_atualiza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BackupNoFechamento {
            get {
                return ((bool)(this["BackupNoFechamento"]));
            }
            set {
                this["BackupNoFechamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection pedidos_colunas_width {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pedidos_colunas_width"]));
            }
            set {
                this["pedidos_colunas_width"] = value;
            }
        }
    }
}
